spring.application.name=JBRO

# contextpath
server.servlet.context-path=/api

# logging level
logging.level.com.kh.menu=debug

# port
server.port=8081

# DataSource
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=admin
spring.datasource.password=jbrotest!

# mybatis
mybatis.mapper-locations=classpath*:/mapper/**/*.xml
mybatis.configuration.jdbc-type-for-null=NULL
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-aliases-package=com.kh

# jwt
jwt.secret=zA0b+x8jnGAjTN6P3c/uzx9q5w29Ya7j4F3auVVRnsg=
jwt.refresh-secret=zA0b+x8jnGAjTN6P3c/uzx9q5w29Ya7j4F3auVVRnsg=

spring.security.oauth2.client.registration.kakao.client-id=21cd93a0d77f57884b9337cfd1f29224
spring.security.oauth2.client.registration.kakao.client-secret=FWlRwRFmJv1sw8MzYGpww9VuZ3AW8YMM
spring.security.oauth2.client.registration.kakao.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.kakao.client-name=Kakao
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.kakao.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.kakao.scope=profile_nickname,profile_image

spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id